services:
    # api
    app-mastering-english:
        container_name: app-mastering-english
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        working_dir: /var/www

        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db-mastering-english
            - httpserver-mastering-english

    # postgreSQL
    db-mastering-english:
        container_name: db-mastering-english
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_HOST_AUTH_METHOD: trust
            PGDATA: /data/postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    # nginx
    httpserver-mastering-english:
        container_name: httpserver-mastering-english
        image: nginx:alpine
        restart: always
        ports:
            - "7777:7777"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d

    redis-mastering-english:
        container_name: redis-mastering-english
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - redis-data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ] # Verifica se o Redis está respondendo
            interval: 30s                      # Intervalo entre verificações
            timeout: 5s                        # Tempo limite da resposta
            retries: 3                         # Tentativas antes de considerar indisponível
            start_period: 10s                  # Espera antes de iniciar verificações

volumes:
    redis-data:
    postgres:
    cache:
        driver: local
