services:
    # api
    app-trotz:
        container_name: app-trotz
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        working_dir: /var/www

        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db-trotz
            - httpserver-trotz

    # postgreSQL
    db-trotz:
        container_name: db-trotz
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_HOST_AUTH_METHOD: trust
            PGDATA: /data/postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    # nginx
    httpserver-trotz:
        container_name: httpserver-trotz
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d

volumes:
    postgres:
    cache:
        driver: local
